### ISSUE TITLE
Allow custom ulx ranks to access logs

### ISSUE THREAD

**Issue by sword134** [myrage2000/ulogs#11]
As the title says. A quick guide on this would be fantastic!

**Comment by myrage2000** [comment]
Yes ok I'll do it

**Comment by sword134** [comment]
i think thats the most friendly github attitude i have ever met. Thank you

**Comment by myrage2000** [comment]
Lol ty
Do you like ulogs ?

**Comment by sword134** [comment]
Its amazing in my opinion! Great work and thanks for releasing it, you deserve more recognition in my opinion.

Sorry for bad english im from Denmark :)

**Comment by myrage2000** [comment]
Ty.
With the last update I added CAMI so ulogs asks CAMI (which is a admin addon compatiblity addon) if the player is (super)admin.
I am going to add a new feature to add more ranks to it (so if you don't have ULX, you can still use the addon with no problem. If you have ULX, you can manage ranks with permissions).

**Comment by sword134** [comment]
Sounds amazing!

**Comment by FindingSum3662** [comment]
ok myrage2000 would you like me to add your addon to the steam workshop for you

**Comment by myrage2000** [comment]
Fixed with the new commit
