### ISSUE TITLE
Add compression to DB

### ISSUE THREAD

**Issue by myrage2000** [myrage2000/ulogs#13]
Add FastLZ compression to the DB but supporting the old logs

**Comment by GGG-KILLER** [comment]
`util.Decompress` basically returns null for non-fastlz strings so you could try to use `util.Decompress` and check for `nil` to see if its legacy logs (and optionally update it in a non-heavy-load manner)

**Comment by myrage2000** [comment]
Yes I know that ^^
Thanks for your support !

**Comment by myrage2000** [comment]
Won't add, it's more cpu-time-consuming than space efficient
