### ISSUE TITLE
MariaDB dosn't support IN LIMIT

### ISSUE THREAD

**Issue by toriato** [myrage2000/ulogs#16]
Query error : This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery' on query : 'DELETE FROM ulogs WHERE id IN( SELECT id FROM ulogs ORDER BY id ASC LIMIT 1)'

I'm using 10.1.10-MariaDB
It's not addon error but I think you can still solve this problem

http://stackoverflow.com/questions/17892762/mysql-this-version-of-mysql-doesnt-yet-support-limit-in-all-any-some-subqu

**Comment by myrage2000** [comment]
Hey
Thanks for the report I'll take a look at it.

**Comment by myrage2000** [comment]
I installed MariaDB, it's working for me
Try to update it please, you might have a older version of it
