### ISSUE TITLE
Problem with damage logs DarkRP

### ISSUE THREAD

**Issue by DutchPatrick** [myrage2000/ulogs#20]
So i use weapon system CW 2.0.
And i saw that damage/kills by that gun didn't got reported into the log menu.
I hope you could help me with this to fix it.

**Comment by myrage2000** [comment]
Hey, it's weird thought it was working on my server.
I'll take a look at it.
Thanks for the report

**Comment by myrage2000** [comment]
I tried again with the last version of CW2, and it's working fine.
Can you please try to reinstall a clean version of ulogs ?
Do you use MySQL ?

**Comment by DutchPatrick** [comment]
I don't use MySQL, i will try to re-install.

**Comment by myrage2000** [comment]
Thanks,
You can also try to reinstall CW2, just in case

**Comment by DutchPatrick** [comment]
Dammit, stil not working.

**Comment by myrage2000** [comment]
Weird...
Do you have any errors in your console ?

**Comment by DutchPatrick** [comment]
Nope.

--------------------------------------------------
Regards,
Patrick


2016-04-14 8:54 GMT+02:00 myrage2000 <notifications@github.com>:
