### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dankerpepers** [myrage2000/ulogs#22]
I'm getting this error:

[ERROR] Query error : no such table: ulogs on query : 'SELECT COUNT(*) AS id FROM ulogs'
1. error - [C]:-1
   1. errorCallback - addons/ultimatelogs/lua/ultimatelogs/server/sv_ultimatelogs.lua:48
   2. query - addons/ultimatelogs/lua/ultimatelogs/server/mysqlite.lua:297
      1. Query - addons/ultimatelogs/lua/ultimatelogs/server/sv_ultimatelogs.lua:56
      2. CheckLimit - addons/ultimatelogs/lua/ultimatelogs/server/sv_ultimatelogs.lua:168
      3. AddLog - addons/ultimatelogs/lua/ultimatelogs/server/sv_ultimatelogs.lua:213
      4. fn - addons/ultimatelogs/lua/ultimatelogs/logtypes/ulogs_admin_ulx.lua:71
         1. Call - addons/ulib/lua/ulib/shared/hook.lua:110
         2. unknown - addons/ulib/lua/ulib/shared/commands.lua:1294
         3. Run - lua/includes/modules/concommand.lua:54
         4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1311
            1. unknown - lua/includes/modules/concommand.lua:54

**Comment by myrage2000** [comment]
Is that error still happening ?
