### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VACSecure** [myrage2000/ulogs#23]
So when i type !logs in chat or type "ulogs" in console nothing happens, no errors pop up, no anything pops up. I do not know if anything is broken or what but it does not work for me.

**Comment by myrage2000** [comment]
Is the addon installed correctly ?
If it does, you should have the "addon.txt" file under : "GarrysMod/garrysmod/addons/ultimatelogs"

Did you restart your server ?

**Comment by akKrzysiu** [comment]
Hello! I have the same problem! I can see the file _"addon.txt"_ under `ulogs-master/ultimatelogs`.

Iam added as _"Superadmin"_ in ulx setting, and it works under _"TAB"_ menu, but it seems I cant use either **"!logs"** or **"ulogs"**. I need help!

**Comment by VACSecure** [comment]
Yes I installed it correctly and restarted the server and nothing appeared

**Comment by akKrzysiu** [comment]
Any help?

**Comment by myrage2000** [comment]
Sorry I wasn't at home.
You have to move the folder called `ultimatelogs/` under `addons/`
Currently, it looks like this :
`addons/ulogs-master/ultimatelogs/`
But the correct path is :
`addons/ultimatelogs`

**Comment by akKrzysiu** [comment]
Wow... Im really dumb for not thinking this out by myself. Thank you Sir! You rock!

**Comment by myrage2000** [comment]
Your welcome, it's a common issue.
