### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Gamerpro2266** [myrage2000/ulogs#24]
[ERROR] Unauthed player
1. query - [C]:-1
   1. fn - addons/ulib-master/lua/ulib/shared/cami_ulib.lua:18
   2. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
      1. PlayerHasAccess - addons/ulib-master/lua/ulib/shared/cami_global.lua:370
      2. GetPlayersWithAccess - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:103
      3. Refresh - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:111
      4. unknown - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:123

**Comment by myrage2000** [comment]
Can you please provide more informations ? (when does this error happen ?, Do you have ULX installed ?, What is your ULX rank ?, Did you edit the (mysql) configuration file ?)

**Comment by Gamerpro2266** [comment]
1/dont know when happens 
2/i use ulx latest
3/i dont even know how to use it

**Comment by myrage2000** [comment]
It's not a Ulogs issue.

**Comment by Gamerpro2266** [comment]
It's got to be becuase when I remove it
It stops the lua

**Comment by Gamerpro2266** [comment]
Or what is causing it

**Comment by myrage2000** [comment]
Ulib or ULX is causing the error

**Comment by myrage2000** [comment]
Fixed with the new commit.
In fact it was not a ulogs issue, but I still fixed it.
