### ISSUE TITLE
Unauthed player error

### ISSUE THREAD

**Issue by myrage2000** [myrage2000/ulogs#25]
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulib/lua/ulib/shared/cami_ulib.lua:18
3. Call - addons/ulib/lua/ulib/shared/hook.lua:109
4. PlayerHasAccess - addons/falco's prop protection/lua/libraries/sh_cami.lua:370
5. GetPlayersWithAccess - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:103
6. Refresh - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:111
7. unknown - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:123

Reported by Sodak on Facepunch

**Comment by thefaiint** [comment]
I got the same error. If you need some additional information let me know

**Comment by MinIsMin** [comment]
This error appears when a user (player/bot) joins the game.
Sometimes it appears serverside, sometimes clientside.

**Comment by Gamerpro2266** [comment]
i told you about this before
https://github.com/myrage2000/ulogs/issues/24

**Comment by SubZero0** [comment]
My stacktrace:
![st](https://cloud.githubusercontent.com/assets/3085008/23490548/fb894ce2-fed7-11e6-949a-1d643da60585.png)

**Comment by myrage2000** [comment]
Fixed
