### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by rivallite** [myrage2000/ulogs#26]
i put the ultimatelog file in my server addons and gmod addons and the auto run in darkrp/entites/autorun if you could show a vidoe or explain more detailed info thx i went in the server typed !logs and then ulogs in console

**Comment by BlueNova00** [comment]
Well all you should need to do it just drop the ultimatelogs folder in the garrysmod/addons directory. I've had the issue of putting ulogs-master in there which proves fruitless as nothing happens. All you should need to do is go into the physical ulogs-master folder and find the ultimatelogs folder and drop it in the garrysmod/addons directory and then restart. Should work fine after that. 

Be sure, though, that you had a database setup and fill in your information in the configuration.lua file that part is also kind of important.

**Comment by myrage2000** [comment]
Right, thanks for your answer @BlueNova00
