### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Losos50** [myrage2000/ulogs#27]
[ERROR] Query error : This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery' on query : 'DELETE FROM ulogs WHERE id IN( SELECT id FROM ulogs ORDER BY id ASC LIMIT 1)'
  1. fn - [C]:-1
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

This is showing and spamming into console, by configuration of ulogs is MySQL turned off and it still creating a table in MySQL when got deleted.

**Comment by myrage2000** [comment]
Hey
The error message is pretty clear : The version of MySQL you are using is outdated.
If it is not, you are probably using a MySQL variant that is not supported yet.

**Comment by Losos50** [comment]
At start of the server it was working, about 30min later when people on the server was online it was starting doing this error.
anyway if the server was online with no players it was working.. maybe small database of MySQL?

**Comment by myrage2000** [comment]
Hey
As I said this is caused by your MySQL version.
You might have another database version.
The error starts about 30 min later because the addon tries to optimize the database at this point.
