### ISSUE TITLE
How do i add Custom ranks to access the ULOGS

### ISSUE THREAD

**Issue by FurryFurret** [myrage2000/ulogs#28]
I try to make a Custom rank to use Ulogs but it says "[Ultimate Logs] You are not allowed to open the logs menu !"

For example (Someone) added Furret to head-dev

Furret: !logs

[Ultimate Logs] You are not allowed to open the logs menu !

**Comment by myrage2000** [comment]
Hey
What admin addon do you have ?
What did you try to change to make this rank able to open the panel ?
