### ISSUE TITLE
!ulogs command

### ISSUE THREAD

**Issue by Robin4123** [myrage2000/ulogs#29]
i typing !logs in the chat and ulogs in the console but nothing happens

**Comment by myrage2000** [comment]
Hey, you may have not installed the addon properly.
"Place the folder 'ultimatelogs' under '*/GarrysMod/addons/'"
You can't place the folder 'ultimatelogs_master' under '*/GarrysMod/addons/'".

If the issue is not solved after that, you should look at the console for errors that could occur
