### ISSUE TITLE
 does not open

### ISSUE THREAD

**Issue by antoinedmk** [myrage2000/ulogs#30]
Something script error 

`[ERROR] addons/ultimatelogs/lua/ultimatelogs/client/cl_ultimatelogs.lua:48: bad argument #1 to 'JSONToTable' (string expected, got boolean)
1. JSONToTable - [C]:-1
2. GetOptions - addons/ultimatelogs/lua/ultimatelogs/client/cl_ultimatelogs.lua:48
3. OpenMenu - addons/ultimatelogs/lua/ultimatelogs/client/cl_ultimatelogs.lua:192
4. func - addons/ultimatelogs/lua/ultimatelogs/client/cl_ultimatelogs.lua:155
5. unknown - lua/includes/extensions/net.lua:32`

**Comment by myrage2000** [comment]
Hey
I'm not sure what is causing this error, I will fix it before Monday.

**Comment by antoinedmk** [comment]
salut c'est moi sur mtx :/ qui a le problem je suis français

**Comment by antoinedmk** [comment]
help :'(

**Comment by MinIsMin** [comment]
@antoinedmk Il écrit qu'il ne sait pas exactement ce que l'erreur est, mais il essaye de le réparer jusqu'à lundi.

**Comment by myrage2000** [comment]
Fixed with update 1.11
