### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by matiasg90** [myrage2000/ulogs#32]
My suggestion is basically to add the automatic removal of the logs
Every certain time that can be configured, or each time the server is reset.

**Comment by myrage2000** [comment]
Hey,
This feature already exists.
You can set a log limit. When this limit is reached, old logs are deleted

**Comment by matiasg90** [comment]
Excuse me, you're right, I did not see it.
Is it possible that there is a problem with sqlite?
I currently have mysql disabled and it works only under mysql

https://i.gyazo.com/fde0919b8603511290465a53d73a8c2e.png
https://i.gyazo.com/1580df46bbfaf41ccfecd1536be97799.png

**Comment by myrage2000** [comment]
No problem.

I didn't understand your problem with sqlite, is the automatic removal not working ?
