### ISSUE TITLE
ULogs just doesnt work.

### ISSUE THREAD

**Issue by mysteriousrunt** [myrage2000/ulogs#35]
When I type !logs into chat it does nothing, and typing ulogs into console just brings up command not recognized. I have Ulogs in my servers addon folder, is there anything else I'm supposed to do to get it to work?

**Comment by myrage2000** [comment]
Hey, dont place ultimatelogs-master under addons/, but the folder "ultimatelogs" instead.
So you will have addons/ultimatelogs/addon.txt.
Then restart your server.
