### ISSUE TITLE
Mysql not working

### ISSUE THREAD

**Issue by TronexEngine** [myrage2000/ulogs#36]
So i setup my mysql but the table that is named logs has nothing in it even tho i did properly configure the mysql config. Do i have to create the tables inside the database myself?

**Comment by myrage2000** [comment]
Hey,
In the config the "database_name" is not the table name, it's the database name (well, no joking x)  )

Then maybe you are talking about the "ulogs_logs" table that is empty...
Do you have any errors in the console when starting the server ?

**Comment by TronexEngine** [comment]
i made a database thats called logs but when i launch the server the database is empty there are no tables no nothing
![untitled](https://user-images.githubusercontent.com/28850156/29744059-b7ddb612-8a6a-11e7-82a7-c61426506c6f.png)

**Comment by myrage2000** [comment]
Hey,
- Do you have any errors when starting the server ?
- Did you install the "mysqloo" module ? It is needed to use MySQL (you can also use tmysql4 but I really don't recommand it).

**Comment by TronexEngine** [comment]
Mysqloo module is installed because the message comes up saying that its up to date.

And no i dont have any errors when starting the server.
![untitled](https://user-images.githubusercontent.com/28850156/29745276-61bca8dc-8a84-11e7-9410-0b3fcf5e6727.png)

**Comment by TronexEngine** [comment]
And here is the screenshot of the database 
![untitled](https://user-images.githubusercontent.com/28850156/29753339-8412d190-8b3d-11e7-8e89-a101381c7005.png)

**Comment by TronexEngine** [comment]
Ok i found the problem. I have 1 database for darkrp and 1 for logs the problem is that the ulogs go together with the darkrp tables.
