### ISSUE TITLE
this is confusing

### ISSUE THREAD

**Issue by strider45** [myrage2000/ulogs#39]
so i download it fom github and extract the folder inside it there is 2 so i extract it and put it in the addons and nothing showed up note i have ULX

**Comment by myrage2000** [comment]
Hey, you may have not installed the addon properly.
"Place the folder 'ultimatelogs' under '/GarrysMod/addons/'"
You can't place the folder 'ultimatelogs_master' under '/GarrysMod/addons/'".

Then you have to issue "!logs" in the chat to open the menu.
You can also take a look at issues : #29 and #26 .
