### ISSUE TITLE
random player joined got this error

### ISSUE THREAD

**Issue by notedhalfling** [myrage2000/ulogs#7]
accidentally submitted way too early
Some random player joined and i got this error

`Error in hook CAMI.PlayerHasAccess: addons/ulib/lua/ulib/shared/cami_ulib.lua:18: [ULIB] Unauthed player
stack traceback:
	[C]: in function 'query'
	addons/ulib/lua/ulib/shared/cami_ulib.lua:18: in function 'fn'
	addons/ulib/lua/ulib/shared/hook.lua:110: in function <addons/ulib/lua/ulib/shared/hook.lua:93>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'
	lua/.dragondildos/rc1/../nul/d37236a9f69d79172cf56d20665c17fe3bdfb2675e4660a8a7675577be361abb.lua:59: in function 'Call'
	addons/ulib/lua/ulib/shared/cami_global.lua:370: in function 'PlayerHasAccess'
	addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:103: in function 'GetPlayersWithAccess'
	addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:111: in function 'Refresh'
	addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:124: in function <addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:124>

[ERROR] addons/ulib/lua/ulib/shared/cami_global.lua:370: 
  1. Call - [C]:-1
   2. PlayerHasAccess - addons/ulib/lua/ulib/shared/cami_global.lua:370
    3. GetPlayersWithAccess - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:103
     4. Refresh - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:111
      5. unknown - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:124

Timer Failed! [ULogs_CAMI_Refresh][@addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua (line 124)]

**Comment by myrage2000** [comment]
Some weeks ago, when I added CAMI to ULogs, I asked ULib's author to fix that issue.
Is your ULX and ULib updated ?

**Comment by notedhalfling** [comment]
it should be but i can check

**Comment by myrage2000** [comment]
I don't think it's a ulogs related issue
Try to update your ulib please.
